# Uncomment the next line to define a global platform for your project
# platform :ios, '13.2'

target 'InStatTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InStatTest

  target 'InStatTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InStatTestUITests' do
    # Pods for testing
  end
	pod 'Alamofire', '~> 5.1'
	pod 'SwiftyJSON', '~> 5.0'
end
